### ISSUE TITLE
체력 -1 되면?

### ISSUE THREAD

**Issue by Hangeol-Chang** [SHT4196/Academia#2]
![image](https://user-images.githubusercontent.com/57909592/144046268-42e4a58d-caaa-48bb-95a3-dfba1dc581c7.png)

이부분 체력 한번에 2 이상 잃어서 체력 -1되면 안죽게 버그날 거 같아요

**Comment by Hangeol-Chang** [comment]
player class 70번째줄입니당

**Comment by haram1117** [comment]
수정했습니다!! 감사합니당
